services:
  app:
    image: st108vm101.rtb-lab.pl/app-server:latest
    deploy:
      restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 10
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 2
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.front==true
    dns:
      - "127.0.0.11"
    networks:
      - overlay

  aggregate_processor:
    image: st108vm101.rtb-lab.pl/aggregate-processor:latest
    deploy:
      endpoint_mode: dnsrr
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.processor==true
    dns:
      - "127.0.0.11"
    networks:
      - overlay

  haproxy:
    image: haproxy:latest
    ports:
      - "8080:8080"
      - "9000:9000"
    volumes:
      - ./cfg/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    deploy:
      placement:
        constraints:
          - node.labels.haproxy==true
    dns:
      - "127.0.0.11"
    networks:
      - overlay

  aerospikedb:
    image: aerospike/aerospike-server-enterprise:latest
    deploy:
      replicas: 5
      endpoint_mode: dnsrr
      placement:
        max_replicas_per_node: 1
        constraints:
          - node.labels.aerospike==true
    labels:
      com.aerospike.cluster: "db"
    volumes:
      - type: bind
        source: /home/st108/aerospike_data
        target: /opt/aerospike/data
    command: ["--config-file", "/run/secrets/aerospike.conf"]
    dns:
      - "127.0.0.11"
    networks:
      - overlay
    secrets:
      - source: aerospike_conf
        target: aerospike.conf
        mode: 0440
      - source: aerospike_key
        target: aerospike-key.conf
        mode: 0440

  aerospike_meshworker:
    image: aerospike/aerospike-tools:latest
    entrypoint:
    - /run/secrets/discovery
    - "--servicename"
    - aerospikedb
    - "-i"
    - "5"
    - "-v"
    deploy:
      placement: 
        constraints: 
                - node.labels.aerospike==true 
    dns: 
        - "127.0.0.11" 
    networks:
      - overlay
    secrets:
    - source: discoveryfile
      target: discovery
      mode: 0750

  controller-1:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    deploy:
      placement:
        constraints:
          - node.labels.kafka-1==true
    dns:
      - "127.0.0.11"
    networks:
      - overlay

  controller-2:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: controller
      KAFKA_LISTENERS: CONTROLLER://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    deploy:
      placement:
        constraints:
          - node.labels.kafka-2==true
    dns:
      - "127.0.0.11"
    networks:
      - overlay


  broker-1:
    image: apache/kafka:latest
    #ports:
    #  - 29092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_MAX_TIMEOUT_MS: 900000
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_NUM_NETWORK_THREADS: 6
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600

    deploy:
      restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 10
      placement:
        constraints:
          - node.labels.kafka-1==true
    dns:
      - "127.0.0.11"
    networks:
      - overlay

  broker-2:
    image: apache/kafka:latest
    #ports:
    #  - 39092:9092
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker-2:19092,PLAINTEXT_HOST://localhost:39092'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@controller-1:9093,2@controller-2:9093
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 2
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_MAX_TIMEOUT_MS: 900000
      KAFKA_NUM_IO_THREADS: 16
      KAFKA_NUM_NETWORK_THREADS: 6
      KAFKA_SOCKET_SEND_BUFFER_BYTES: 102400
      KAFKA_SOCKET_RECEIVE_BUFFER_BYTES: 102400
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 104857600
    deploy:
      restart_policy:
              condition: on-failure
              delay: 5s
              max_attempts: 10
      placement:
        constraints:
          - node.labels.kafka-2==true
    dns:
      - "127.0.0.11"
    networks:
      - overlay
        

networks:
    overlay:
      driver: overlay
      attachable: true
                
secrets:
  aerospike_conf:
      file: ./cfg/aerospike/aerospike.conf
  aerospike_key:
      file: ./cfg/aerospike/feature-key.conf
  discoveryfile:
      file: ./cfg/aerospike/discovery.py
